name: Blog project CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Compose up ...
      run: docker-compose up -d
    - name: run tests
      run: docker exec backend sh -c "pytest ."
